# Nome do workflow
name: CI/CD Pipeline - Build, Push e Deploy

# 1. Gatilho (Trigger)
on:
  push:
    branches: [ main ]

jobs:
  build-push-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código da aplicação
        uses: actions/checkout@v3

      - name: Login no Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 4. Extrai o SHA do commit
      - name: Extrair SHA do commit
        id: vars
        run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      # 5. Build e Push da Imagem Docker
      - name: Build and push da imagem Docker
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/compass-python-api:${{ steps.vars.outputs.sha_short }}

      # 6. Checkout do Repositório de Manifestos (GitOps)
      - name: Checkout repositório de manifestos
        uses: actions/checkout@v3
        with:
          repository: ${{ github.repository_owner }}/compass-kubernetes-deployments
          ssh-key: ${{ secrets.SSH_PRIVATE_KEY }}
          path: manifests

      # 7. Atualizar o arquivo de deployment
      - name: Atualizar a tag da imagem no deployment
        run: |
          cd manifests
          sed -i 's|image: ${{ secrets.DOCKER_USERNAME }}/compass-python-api:.*|image: ${{ secrets.DOCKER_USERNAME }}/compass-python-api:${{ steps.vars.outputs.sha_short }}|' deployment.yaml

      # 8. Fazer o Commit e Push da mudança no manifesto
      - name: Commit e Push das mudanças no manifesto
        run: |
          cd manifests
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add deployment.yaml
          git diff-index --quiet HEAD || git commit -m "ci: atualiza tag da imagem para ${{ steps.vars.outputs.sha_short }}"
          git push